version: '3.8'
services:
  postgres:
    build:
      context: .
      dockerfile: postgresDB/Dockerfile
    image: 1310198913101989/chatbot_postgres_k8s
    container_name: chatbot_postgres_k8s
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "5432:5432"
    networks:
      - my_network
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./postgresDB/init-scripts:/docker-entrypoint-initdb.d

  backend:
    build:
      context: .
      dockerfile: src/Dockerfile
    container_name: chatbot_backend_k8s
    image: 1310198913101989/chatbot_backend_k8s
    ports:
      - "8000:8000"
    environment:
      OPENAI_KEY: ${OPENAI_KEY}
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_HOST: ${POSTGRES_HOST}
    depends_on:
      - postgres
    networks:
      - my_network

  docs:
    build:
      context: .
      dockerfile: docs/Dockerfile
    container_name: chatbot_docs_k8s
    image: 1310198913101989/chatbot_docs_k8s
    ports:
      - "8001:8001"
    depends_on:
      - backend
    networks:
      - my_network

networks:
  my_network:
    driver: bridge

volumes:
  postgres_data:

# docker-compose up --build
# docker push 1310198913101989/chatbot_backend_k8s
# docker push 1310198913101989/chatbot_postgres_k8s
# docker push 1310198913101989/chatbot_docs_k8s
# docker push 1310198913101989/chatbot_backend
# docker push 1310198913101989/chatbot_postgres
# docker push 1310198913101989/chatbot_docs

# for local container app to work you need to change ${POSTGRES_HOST} to postgres here and in main.py file