version: '3.8'
services:
  postgres:
    image: postgres:latest
    container_name: app-postgres_db
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    networks:
      - my_network
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./postgresDB/init-scripts:/docker-entrypoint-initdb.d

  app:
    build:
      context: .
      dockerfile: src/Dockerfile
    container_name: app-backend
    ports:
      - "8000:8000"
    environment:
      - OPENAI_KEY=${OPENAI_KEY}
    depends_on:
      - postgres
    networks:
      - my_network

  docs:
    build:
      context: .
      dockerfile: docs/Dockerfile
    container_name: app-docs
    ports:
      - "8001:8001"
    depends_on:
      - app
    networks:
      - my_network

networks:
  my_network:
    driver: bridge

volumes:
  postgres_data:

# docker-compose up --build