version: '3.8'
services:
  postgres:
    build:
      context: .
      dockerfile: postgresDB/Dockerfile
    image: 1310198913101989/chatbot_postgres
    container_name: chatbot_postgres
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "5432:5432"
    networks:
      - my_network
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./postgresDB/init-scripts:/docker-entrypoint-initdb.d

  app:
    build:
      context: .
      dockerfile: src/Dockerfile
    container_name: chatbot_backend
    image: 1310198913101989/chatbot_backend
    ports:
      - "8000:8000"
    environment:
      OPENAI_KEY: ${OPENAI_KEY}
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_HOST: ${POSTGRES_HOST}
    depends_on:
      - postgres
    networks:
      - my_network

  docs:
    build:
      context: .
      dockerfile: docs/Dockerfile
    container_name: chatbot_docs
    image: 1310198913101989/chatbot_docs
    ports:
      - "8001:8001"
    depends_on:
      - app
    networks:
      - my_network

networks:
  my_network:
    driver: bridge

volumes:
  postgres_data:

# docker-compose up --build
# docker push 1310198913101989/chatbot_backend
# docker push 1310198913101989/chatbot_postgres
# docker push 1310198913101989/chatbot_docs