apiVersion: v2
name: chatbot
description: A Helm chart for Kubernetes to deploy the chatbot application
type: application
version: 0.0.1
appVersion: "1.0"


# k create namespace chatbot
# k get ns

# k config get-contexts
# k config set-context --current --namespace=chatbot

# helm create k8s
# helm install chatbot .
# helm uninstall chatbot

# k get pods -n chatbot
# k logs chatbot-6694877865-gss25
# k get pods --show-labels

# k get services -n chatbot
# k describe service chatbot

