replicaCount: 1

images:
  chatbot_backend_fastapi:
    name: chatbot-backend-fastapi
    repository: docker.io/1310198913101989/chatbot_backend_fastapi:latest
    pullPolicy: IfNotPresent
  chatbot_docs:
    name: chatbot-docs
    repository: docker.io/1310198913101989/chatbot_docs:latest
    pullPolicy: IfNotPresent
  chatbot_db_postgres:
    name: chatbot-db-postgres
    repository: docker.io/1310198913101989/chatbot_db_postgres:latest
    pullPolicy: IfNotPresent

services:
  backend_fastapi_service:
    type: ClusterIP
    protocol: TCP
    port: 8000
    targetPort: 8000
    nodePort: 30080
  docs_service:
    type: ClusterIP
    protocol: TCP
    port: 8001
    targetPort: 8001
    nodePort: 30081
  db_postgres_service:
    type: ClusterIP
    protocol: TCP
    port: 5432
    targetPort: 5432
    nodePort: 30432
