replicaCount: 1

images:
  chatbot_backend_fastapi:
    name: chatbot-backend-fastapi
    repository: docker.io/1310198913101989/chatbot_backend_fastapi:latest
    pullPolicy: IfNotPresent
  chatbot_docs:
    name: chatbot-docs
    repository: docker.io/1310198913101989/chatbot_docs:latest
    pullPolicy: IfNotPresent
  chatbot_db_postgres:
    name: chatbot-db-postgres
    repository: docker.io/1310198913101989/chatbot_db_postgres:latest
    pullPolicy: IfNotPresent

services:
- name: backend-fastapi-service
  type: ClusterIP
  port: 8000
  targetPort: 8000
- name: docs-service
  type: ClusterIP
  port: 8001
  targetPort: 8001
- name: db-postgres-service
  type: ClusterIP
  port: 5432
  targetPort: 5432