replicaCount: 1

images:
- name: chatbot_backend_fastapi
  repository: docker.io/1310198913101989/chatbot_backend_fastapi:latest
  pullPolicy: IfNotPresent
- name: chatbot_docs
  repository: docker.io/1310198913101989/chatbot_docs:latest
  pullPolicy: IfNotPresent
- name: chatbot_db_postgres
  repository: docker.io/1310198913101989/chatbot_db_postgres:latest
  pullPolicy: IfNotPresent

services:
- name: chatbot_backend_fastapi
  type: ClusterIP
  port: 8000
  targetPort: 8000
- name: chatbot_docs
  type: ClusterIP
  port: 8001
  targetPort: 8001
- name: chatbot_db_postgres
  type: ClusterIP
  port: 5432
  targetPort: 5432