apiVersion: v1
kind: Service
metadata:
  name: {{ include "chatbot.fullname" . }}
  labels:
    {{- include "chatbot.labels" . | nindent 4 }}
spec:
  # type: NodePort
  selector:
    app.kubernetes.io/name: {{ include "chatbot.fullname" . }}
  ports:
    - name: {{ .Values.services.backend_fastapi_service.name }}
      protocol: {{ .Values.services.backend_fastapi_service.protocol }}
      port: {{ .Values.services.backend_fastapi_service.port }}
      targetPort: {{ .Values.services.backend_fastapi_service.targetPort }}
      # nodePort: {{ .Values.services.backend_fastapi_service.nodePort }}
    - name: {{ .Values.services.docs_service.name }}
      protocol: {{ .Values.services.docs_service.protocol }}
      port: {{ .Values.services.docs_service.port }}
      targetPort: {{ .Values.services.docs_service.targetPort }}
      # nodePort: {{ .Values.services.docs_service.nodePort }}
    - name: {{ .Values.services.db_postgres_service.name }}
      protocol: {{ .Values.services.db_postgres_service.protocol }}
      port: {{ .Values.services.db_postgres_service.port }}
      targetPort: {{ .Values.services.db_postgres_service.targetPort }}
      # nodePort: {{ .Values.services.db_postgres_service.nodePort }}
