apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "k8s.fullname" . }}
  labels:
    {{- include "k8s.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "k8s.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "k8s.selectorLabels" . | nindent 8 }}
    spec:
      containers:
        - name: {{ .Values.images.chatbot_backend_fastapi.name }}
          image: {{ .Values.images.chatbot_backend_fastapi.repository }}
          imagePullPolicy: {{ .Values.images.chatbot_backend_fastapi.pullPolicy }}
          ports:
            - name: http
              containerPort: 8000
              protocol: TCP

        - name: {{ .Values.images.chatbot_docs.name }}
          image: {{ .Values.images.chatbot_docs.repository }}
          imagePullPolicy: {{ .Values.images.chatbot_docs.pullPolicy }}
          ports:
            - name: http
              containerPort: 8001
              protocol: TCP
        - name: {{ .Values.images.chatbot_db_postgres.name }}
          image: {{ .Values.images.chatbot_db_postgres.repository }}
          imagePullPolicy: {{ .Values.images.chatbot_db_postgres.pullPolicy }}
          ports:
            - name: http
              containerPort: 5432
              protocol: TCP
