apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingress-backend
spec:
  rules:
    - host: localhost
      http:
        paths:
          - path: /postgres
            pathType: Prefix
            backend:
              service:
                name: {{ include "chatbot.fullname" . }}-db-postgres-service
                port:
                  number: 5432