apiVersion: v1
kind: Service
metadata:
  name: {{ include "k8s.fullname" . }}-backend-fastapi-service
  labels:
    {{- include "k8s.labels" . | nindent 4 }}
spec:
  selector:
    app: {{ include "k8s.fullname" . }}
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 8000

apiVersion: v1
kind: Service
metadata:
  name: {{ include "k8s.fullname" . }}-docs-service
  labels:
    {{- include "k8s.labels" . | nindent 4 }}
spec:
  selector:
    app: {{ include "k8s.fullname" . }}
  ports:
    - protocol: TCP
      port: 8001
      targetPort: 8001

apiVersion: v1
kind: Service
metadata:
  name: {{ include "k8s.fullname" . }}-db-postgres-service
  labels:
    {{- include "k8s.labels" . | nindent 4 }}
spec:
  selector:
    app: {{ include "k8s.fullname" . }}
  ports:
    - protocol: TCP
      port: 5432
      targetPort: 5432