apiVersion: v1
kind: Service
metadata:
  name: {{ include "chatbot.fullname" . }}
  labels:
    {{- include "chatbot.labels" . | nindent 4 }}
spec:
  selector:
    app: {{ include "chatbot.fullname" . }}
  ports:
    - name: backend
      protocol: TCP
      port: 8000
      targetPort: 8000
    - name: docs
      protocol: TCP
      port: 8001
      targetPort: 8001
    - name: postgres
      protocol: TCP
      port: 5432
      targetPort: 5432