{{- range .Values.services }}
apiVersion: v1
kind: Service
metadata:
  name: {{ .name }}
  labels:
    {{- include "chatbot.labels" . | nindent 4 }}
spec:
  type: {{ .type }}
  ports:
    - protocol: TCP
      port: {{ .port }}
      targetPort: {{ .targetPort }}
  selector:
    {{- include "chatbot.selectorLabels" . | nindent 6 }}
{{- end }}